name: docker-tinycore

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron:  "* * */2 * *" # At 00:00 in every month.
  workflow_dispatch:

jobs:
  image:
    name: docker-tinycore
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "🛠️ Build"
        run: make all -j1
      - name: "Retag image"
        run: |
            docker images --filter=reference='tinycore' --format='{{.Repository}}:{{.Tag}}' | xargs -r -P$(nproc) -I {} docker image tag {} bensuperpc/{}
            docker image tag bensuperpc/tinycore:12.0-x86_64 bensuperpc/tinycore:latest
      - name: "Logging to docker"
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: "📤 Upload to hub.docker.com"
        run: docker push bensuperpc/tinycore --all-tags
      - name: "🧹 Clean"
        run: make clean


